//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebNgheNhac.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ALBUM
    {
        public int MA_AB { get; set; }
        public string TEN_AB { get; set; }
        public string ANH_AB { get; set; }
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> NGAYPHATHANH { get; set; }
        public Nullable<int> LUOTNGHE { get; set; }
        public string THONGTIN { get; set; }
        public Nullable<int> MA_TL { get; set; }
        public Nullable<int> MA_CS { get; set; }
    
        public virtual CASI CASI { get; set; }
        public virtual THELOAI THELOAI { get; set; }
    }
}
